[package]
name = "holly"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust_socketio = "0.3.0"
serde = "1.0"
serde_json = "1.0"
reqwest = { version = "0.11.0", features = ["multipart"] }
